all:
	#g++ -g -o o main.cpp Module.cpp -lzrandom
	#g++ -g -o o test1.cpp Module.cpp -lzrandom
	#g++ -g -o o test2.cpp Module.cpp -lzrandom
	#g++ -g -o o test3.cpp Module.cpp -lzrandom
	#g++ -g -o o test4.cpp Module.cpp -lzrandom
	#g++ -g -o o test5.cpp Module.cpp -lzrandom
	#g++ -g -o o test6.cpp Module.cpp -lzrandom
	#g++ -g -o o test7.cpp Module.cpp -lzrandom
	g++ -g -o o test_random_mutation.cpp Module.cpp -lzrandom
